version: '3'

networks:
  proxy:
    external: true
  mongo:
    internal: true

services:
  ffxiv:
    image: maael/ffxiv:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/ffxiv
    labels:
      - traefik.backend=ffxiv
      - traefik.frontend.rule=Host:ffxiv.mael.tech
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - proxy
      - mongo

  mongo:
    image: mongo
    hostname: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    volumes:
      - ./data/db:/data/db
      - ./data/log:/data/log
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    labels:
      - traefik.backend=ffxiv-db
      - traefik.frontend.rule=Host:ffxiv-db.mael.tech
      - traefik.docker.network=proxy
      - traefik.port=8081
    networks:
      - proxy
      - mongo
